// auth

export const AUTHORIZE_SERVICE = 'USER/AUTHORIZE_SERVICE'
export const UNAUTHORIZE_SERVICE = 'USER/UNAUTHORIZE_SERVICE'

// songs

export const INCREMENT_NONCE = 'SONGS/INCREMENT_NONCE'
export const SET_SONG_PLAYLIST = 'SONGS/SET_SONG_PLAYLIST'
export const ADD_TO_RECENTLY_PLAYED = 'SONGS/ADD_TO_RECENTLY_PLAYED'
export const SET_SONG_REPEAT = 'SONGS/SET_SONG_REPEAT'
export const SET_SONG_VOLUME = 'SONGS/SET_SONG_VOLUME'
export const SET_SONG_MUTE = 'SONGS/SET_SONG_MUTE'

export const PLAY_NEXT = 'SONGS/PLAY_NEXT'
export const PLAY_LATER = 'SONGS/PLAY_LATER'
export const PLAY_PREVIOUS = 'SONGS/PLAY_PREVIOUS'

export const SONG_PLAY = 'SONGS/SONG_PLAY'
export const SONG_PAUSE = 'SONGS/SONG_PAUSE'

export const SHOW_SONG_CONTEXTMENU = 'SONGS/SHOW_SONG_CONTEXTMENU'

// routes

export const NAVIGATE_TO = 'ROUTES/NAVIGATE_TO'

